### ISSUE TITLE
default forwarders not copied to volume mount

### ISSUE THREAD

**Issue by telnetdoogie** [MatthewVance/unbound-docker#108]
**Describe the bug**
If I use a volume mount , for example:
```
    volumes:
      - /volume1/docker/unbound/config:/opt/unbound/etc/unbound:rw
```
Then upon first run the default `unbound.conf` file is copied / created in the mount on the host system, so that it can be edited etc., however that breaks the default config because the three files:
```
/opt/unbound/etc/unbound/a-records.conf
/opt/unbound/etc/unbound/srv-records.conf
/opt/unbound/etc/unbound/forward-records.conf
```
are not exposed in that same folder structure.

That creates a situation where the default config becomes invalid (as it includes those files for forwarders) and the container fails to start.

This appears to be a side-effect of when the `unbound.conf` file is created initially (by `unbound.sh`) on initial container creation, whereas the forwarded config files are pulled as part of the original image and unless they're re-copied on container initialization, they will not be present in the mounted volume.

It's highly desirable to also expose those files so that users can customize their config without having to re-create these files.

**To Reproduce**
1. Use compose file:
```services:
  unbound:
    image: mvance/unbound:latest
    network_mode: bridge
    container_name: unbound
    restart: unless-stopped
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    environment:
      - TZ=America/Chicago
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ${DOCKER_FOLDER}/unbound/config:/opt/unbound/etc/unbound:rw
```
2. run `docker-compose up`
3. container will error about the missing include files and abend

**Expected behavior**
I would expect those included config files to be exposed in the same way the `unbound.conf` file is exposed when using a mounted volume.

...Opening this Issue to capture my thoughts. I may try to take a look and see if I can submit a resolution but... I'm not sure of my capabilities to do so. See related reddit post here:
https://www.reddit.com/r/unRAID/comments/nn5ea3/comment/il36lun/

**Comment by telnetdoogie** [comment]
Without mounted volume, from within the container:
```
# ls -al
total 80
drwxr-xr-x 1 root     root       198 Aug 20 12:41 .
drwxr-xr-x 1 root     root        14 Jul 12 21:18 ..
-rw-r--r-- 1 root     root       135 Jul 12 21:16 a-records.conf
drwxr-xr-x 1 root     root        34 Aug 20 12:41 dev
-rw-r--r-- 1 root     root      2170 Jul 12 21:16 forward-records.conf
-rw-r--r-- 1 root     root        95 Jul 12 21:16 srv-records.conf
-rw-r--r-- 1 root     root     13361 Aug 20 12:41 unbound.conf
-rw-r--r-- 1 root     root     47765 Jul 12 21:26 unbound.conf.example
-rw-r--r-- 1 _unbound _unbound     2 Aug 20 12:41 unbound.pid
drwx------ 1 _unbound _unbound    16 Aug 20 12:41 var
# pwd
/opt/unbound/etc/unbound
```

With mounted volume:
```
# ls -al
total 20
drwxr-xr-x 1 root     root        58 Aug 20 11:53 .
drwxr-xr-x 1 root     root        14 Jul 12 21:18 ..
drwxr-xr-x 1 root     root        34 Aug 20 12:43 dev
-rw-r--r-- 1 root     root     13364 Aug 20 11:53 unbound.conf
-rw-r--r-- 1 _unbound _unbound     2 Aug 20 12:43 unbound.pid
drwx------ 1 _unbound _unbound    16 Aug 20 12:43 var
# pwd
/opt/unbound/etc/unbound
```

**Comment by telnetdoogie** [comment]
It appears that the `unbound.conf` file is freshly created from the `unbound.sh` script when the container is created, so I assume that's why it is created on the volume whereas the .conf files are already part of the image. Perhaps a solution might be to have those files in a separate folder (or created at init in a seperate folder, in the case of `unbound.conf`) and then copied to the destination at the end of the initial container creation... that way they'd all be present in the external volume.

**Comment by MatthewVance** [comment]
Yes, ` unbound.conf` is created by the `unbound.sh` if it doesn't exist:

https://github.com/MatthewVance/unbound-docker/blob/7e369e727519d3718b682dfa66a5791150db57df/1.16.1/data/unbound.sh#L34

If you provide your own ` unbound.conf` at launch, you're in full control of how files are included. The default provided with this image includes them as separate files:

https://github.com/MatthewVance/unbound-docker/blob/7e369e727519d3718b682dfa66a5791150db57df/1.16.1/data/unbound.sh#L344-L351

This is done so they can be provided individually as volume mounts without having to fully customize the `unbound.conf`. This makes it easir for someone to provide different a-records, srv records, and forward files.

**Comment by MatthewVance** [comment]
This is behavior I don't intend to change.

For unbound, I recommend against mounting a volume as read/write. Read-only is more secure. If you need to customize the config, do so before it's launched. Containers are fast to re-start and meant to be ephemeral. Editing a config of a running container seems like an anti-pattern.

**Comment by telnetdoogie** [comment]
👍 

This makes sense, and I appreciate the info... so, don't mount with `:rw`, rather use `:ro`
and you (I) should (if so inclined) mount the individual files versus the `/opt/unbound/etc/unbound` folder itself?

I think the reason I was looking at this originally is because I was looking to make sure my unbound instance is a recursive only solution and NOT a forwarder, hence why I was trying to remove the forwarder config.

**Comment by telnetdoogie** [comment]
...and perhaps my simplest solution to remove forwarding would be to just create my own (perhaps empty) `/opt/unbound/etc/unbound/forward-records.conf` and not have to worry about `unbound.conf` - is that a preferred solution?

**Comment by MatthewVance** [comment]
Sure thing. This is more my preference than a requirement.

To remove forwarding, you'll need to edit the `unbound.conf`. As long as you don't have something like `include: /opt/unbound/etc/unbound/forward-records.conf` in your config, it shouldn't expect a `forward-records.conf` file to exist so you won't have to worry about providing an empty one.

I think the issue you ran into happened because you were trying to edit a running container that used the default unbound.conf file that was created at launch. The supporting files are also provided in the default state. 

If you launch with a custom config  setup as a a recursive solution, you should be good to go without adding any other files in your volume mount. Hopefully, this makes sense.

**Comment by telnetdoogie** [comment]
Super appreciate the explanation!!! Thanks so much!! 

And thanks for the awesome image!

**Comment by telnetdoogie** [comment]
Thanks so much for the insights @MatthewVance... My docker-compose.yml now looks like this and I think that's a much cleaner way to go... I'm learning every day!

```
services:

  unbound:
    image: mvance/unbound:latest
    network_mode: bridge
    container_name: unbound
    restart: unless-stopped
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    environment:
      - TZ=America/Chicago
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ${DOCKER_HOME}/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
```

Now I don't have to worry about any other files or folders, just remove the forwarders from the config. Super appreciate!!

**Comment by MatthewVance** [comment]
Why would the config file need to be edited when a container is running? Why not just relaunch the container?

**Comment by telnetdoogie** [comment]
It doesn’t. Based on your previous comments / suggestions this is a non-issue. If folks want a custom config they can provide one, and mount it as above. If not, no volume / file mounts are needed. closed issue
