### ISSUE TITLE
Is this line [in]correct?

### ISSUE THREAD

**Issue by telnetdoogie** [MatthewVance/unbound-docker#109]
https://github.com/MatthewVance/unbound-docker/blob/eb042c27059e805bf38dc0f60f5672340fb61d36/1.16.1/Dockerfile#L119

I'm wondering if this line should be:

`useradd -g _unbound -s /bin/false -d /etc _unbound && \`

...it feels like the `shell` and `home dir` params are reversed, and the shell uses `/dev/null` instead of `/bin/false`??

**Comment by MatthewVance** [comment]
-s, --shell SHELL
The name of the user's login shell. The default is to leave this field blank, which causes the system to select the default login shell specified by the SHELL variable in /etc/default/useradd, or an empty string by default.

-d, --home HOME_DIR
The new user will be created using HOME_DIR as the value for the user's login directory. The default is to append the LOGIN name to BASE_DIR and use that as the login directory name. The directory HOME_DIR does not have to exist but will not be created if it is missing.

**Comment by MatthewVance** [comment]
You're right, it's reversed and should be updated.

The `-s` sets the shell. It's set to `/etc` but should be `/dev/null`. `/bin/false` would work also.

The `-d` sets the home directory. It's set to `/dev/null` but should be `/etc`.

**Comment by MatthewVance** [comment]
I'm working on a fix for this.

**Comment by telnetdoogie** [comment]
fixed by @MatthewVance in d7055cc5c8bf15ed904a912ee8bb5dfeeecf7414

**Comment by MatthewVance** [comment]
@telnetdoogie thanks. Somehow I lost an earlier commit and included part of the fix in https://github.com/MatthewVance/unbound-docker/commit/d7055cc5c8bf15ed904a912ee8bb5dfeeecf7414. It should be fully resolved now.
