### ISSUE TITLE
Root.hints file

### ISSUE THREAD

**Issue by MuadDibIII** [MatthewVance/unbound-docker#117]
Hello,

Today I use a unbound server as an authoritative DNS server on a small Raspberry Pi that I have home, and I use it with a Pi-hole that I have installed on a Synology Docker container.

After finding your project, I thought I could use both o my NAS, simplifying the maintenance, updates, ...

But on the other side, the container updates are also important, since the root.hints file needs to be updated on a fair basis (not frequently, but updated every once and then). I try to find some clue on the description or on the open issues and I found nothing regarding this file.

Does it "come" inside the container or I would have to add it and then configure my unbound.conf file in order to use it?

Thanks in advance for your help,

Best regards,
Marc

**Comment by MatthewVance** [comment]
Hi Marc, this should help: https://github.com/MatthewVance/unbound-docker/issues/28#issuecomment-541953720

**Comment by MuadDibIII** [comment]
Hello Matthew,

Thanks for the reply, I'll try o deploy it and see what happens.

Best regards,
Marc
