### ISSUE TITLE
unbound control suddenly fails with control-enable is 'no' 

### ISSUE THREAD

**Issue by hanscees** [MatthewVance/unbound-docker#123]
**Describe the bug**
I control the dns server from another linux host by using unbound-control
This has worked fine for three years or more. 
After update of linux host (so not the server) this fails with error 

'
sudo unbound-control -c ~/keys/unbound.conf -s 192.168.0.110@953  local_data homeassistant2.hanscees.com A 192.168.0.64
[1675281728] unbound-control[12204:0] warning: control-enable is 'no' in the config file.
[1675281728] unbound-control[12204:0] fatal error: could not recv: Connection reset by peer
'

**Expected behavior**
unbound-controll addition to A record should yield no error

**Error messages**
If applicable, include error messages to help explain your problem.

**Additional context**

server version = unbound 1.8.3.
unbound-control on host version 1.16.2

**Comment by hanscees** [comment]
also found the solution.

apparently since recently the unbound.conf file on the unbound-control client side needs this:

'
remote-control:
    control-enable: yes

'

thats new. Works again. 
So the client gave an error, including " reset by peer" but the server did not give that error. 
Pretty confusing. 

but solved

**Comment by MatthewVance** [comment]
That is odd. Thank you for reporting and posting the solution for others to find.
