### ISSUE TITLE
Alpine docker image?

### ISSUE THREAD

**Issue by Gontier-Julien** [MatthewVance/unbound-docker#129]
**Is your feature request related to a problem? Please describe.**
A alpine version of the docker image would be great! It use less space and thus the docker image is smaller, it also more secure than debian.

**Describe the solution you'd like**
Have a version of the image which use alpine for the container aside of the debian version. (which can use the -slim variant to be more lightweight)

**Describe alternatives you've considered**
Alpine Linux

**Additional context**
[Alpine docker image](https://hub.docker.com/_/alpine/)
[Official Alpine website](https://www.alpinelinux.org/)

**Comment by Gontier-Julien** [comment]
Also if needed i could help work on it and/or maintain it ^^

**Comment by MatthewVance** [comment]
Thanks for the suggestion and linking to another version that already supports Alpine. I plan to keep this one on Debian for now.
