### ISSUE TITLE
Unbound's custom port does not work with Pi-hole!

### ISSUE THREAD

**Issue by AFGreeneye** [MatthewVance/unbound-docker#134]
Hello guys! I hope all of you are doing fine! As I mentioned in the title, Since Pi-hole uses port 53, my Unbound's custom port does not work with Pi-hole!

`docker run --name unbound -d -p 5335:53/udp -p 5335:53/tcp  --restart=always mvance/unbound:latest`

If there Is a config file to make/edit to solve this problem, please help me with that. Thank you so much.

**Comment by MatthewVance** [comment]
It can work. This comment shows a setup: https://github.com/MatthewVance/unbound-docker/issues/120#issuecomment-1363477286
