### ISSUE TITLE
Unbound Healthcheck fails every time.  NSLOOKUP fails within the Container, but not from the linux shell. 

### ISSUE THREAD

**Issue by DaEmbassy** [MatthewVance/unbound-docker#137]
**Describe the bug**
I am running a pihole container and an unbound container on an Ubuntu server.
The status of the pihole is always healthy.
The unbound container health status changes from 'starting' to 'unhealthy' a couple of minutes after starting the container.  The container never has a healthy status.

**To Reproduce**
1. Start the unbound container
2. Wait three minutes
3. Execute 'docker ps'
4. Examine the status of the unbound container.  For instance the output of 'docker ps' for me at this minute:

CONTAINER ID   IMAGE                  COMMAND         CREATED          STATUS                      PORTS                                                                                                                                                    NAMES
8e8547e01608   my-unbound             "/unbound.sh"   41 minutes ago   Up 41 minutes (unhealthy)   53/tcp, 53/udp, 0.0.0.0:5335->5335/tcp, 0.0.0.0:5335->5335/udp, :::5335->5335/tcp, :::5335->5335/udp                                                     unbound
12a3eaa00636   pihole/pihole:latest   "/s6-init"      3 hours ago      Up 3 hours (healthy)        0.0.0.0:53->53/tcp, :::53->53/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:53->53/udp, :::443->443/tcp, :::53->53/udp, 67/udp   pihole

**Expected behavior**
I expect the unbound container health status to be "healthy" once the container gets past status 'starting'.
I want the health check to execute successfully - that is, the nslookup of www.google.com using unbound should work from within the unbound container.

**Error messages**
When I execute 'docker exec -it unbound nslookup www.google.com 127.0.0.1' ' then the return message is ';; connection timed out; no servers could be reached'
From the shell when I execute ' nslookup www.google.com 127.0.0.1' then the return message is 'Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   www.google.com
Address: 172.217.167.68
Name:   www.google.com
Address: 2404:6800:4006:80a::2004'

**Additional context**
'nslookup' was not included in the latest unbound container.  Which confuses me, as it is mentioned as a part of the Health Check for the container : HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=1 CMD nslookup www.google.com 127.0.0.1 || exit 1

So I created a Dockerfile containing "FROM mvance/unbound:latest \ RUN apt update && apt-get install -y bind9-dnsutils" and created a new instance 'my-unbound'.  This is the container I have been using.

I include the shell script to start the container here, as well as the configuration file for unbound.

[docker_run_unbound.txt](https://github.com/MatthewVance/unbound-docker/files/12095047/docker_run_unbound.txt)
[unbound_conf.txt](https://github.com/MatthewVance/unbound-docker/files/12095070/unbound_conf.txt)

**Comment by DaEmbassy** [comment]
I am grateful for your quick response @MatthewVance 

I looked over the notes you referred me to for #120 and I copied a ton of settings from your [unbound.conf] into mine.
I restarted the unbound instance, and now I regret to say that the instance restarts itself every minute.
Clearly I've made my own situation worse, but don't know how.
I'll paste my new configuration file in here - but it's late now and I'll look again in daylight.  I don' t know how I've made it worse!
[unbound_conf.txt](https://github.com/MatthewVance/unbound-docker/files/12096308/unbound_conf.txt)

**Comment by MatthewVance** [comment]
@DaEmbassy thanks for looking all of that over. The unbound.conf example makes some assumptions about other aspects of the setup. Copying settings over verbatim may not work. For instance, it expects volumes to be mounted a certain way and referenced files to be at the right places.

Earlier, when you said the following, was that the shell after you got after running `docker exec` to access a shell _in_ the container or was it from the shell of your _host_ machine?: 

> From the shell when I execute ' nslookup [www.google.com](http://www.google.com/) 127.0.0.1' then the return message is 'Server: 127.0.0.1
> Address: 127.0.0.1#53

When running nslookup (or drill, dig, etc.), make sure to use a flag to tell it to query against a different port if necessary. In the example docker-compose I linked to, port 5353 was published for Unbound so that Pi-hole could use 53 on the host.

I recommend getting  your Unbound config setup to work on its own before adding in Pi-hole. Reducing variables and complexity will make narrowing down the issue easier.

You may even want to try it with Docker run commands before converting it to a compose setup because most of the readme documentation shows that method. I recommend not using in `--restart` either until everything is working as you want.

You'll likely want a recursive setup as your starting place: https://github.com/MatthewVance/unbound-docker#recursive-config.

Unfortunately, the default healthcheck logic included with the image has a flaw in it: https://github.com/MatthewVance/unbound-docker/issues/112.

**Comment by DaEmbassy** [comment]
Running dig or nslookup or ping from my host machine, from the default shell, just works.
But ping and dig and nslookup from the latest mvance/Unbound container are absent, so I added nslookup to the instance so i could run that command from within docker.  It's from within docker that DNS resolution is not working.  This problem is made obvious by the Health of the container because the health check fails about a minute after starting the container.

I had Pihole and Unbound running well all this year; and then I decided to get Docker installed and change over to running containerised Pihole and containerised Unbound.  Pihole works fine, but Unbound will just not work, and I've spent between 1 and 2 days of effort so far attempting to getting the Unbound container to work.  I can't believe how challenging it is to just replicate a working application when it is containerised.

There is no need for me to change the Pihole configuration, it already works.  I'll spend a couple more hours stripping back the Unbound configuration and seeing if that allows Unbound to stop spontaneously restarting, and if I can get DNS resolution to work inside Docker.   For a start I'll eliminate --restart and eliminate the performance settings, and minimise the security settings, just to see if Unbound will get some stability.

Thanks for taking the time to offer your ideas, Matthew.

**Comment by MatthewVance** [comment]
I'm sorry to hear you're having so much trouble. I know how frustrating it can be to get something like this working.

Drill should be available in the container. I know its not as commonly used, but it kept the image cleaner by not requiring extra packages.

**Comment by DaEmbassy** [comment]
@MatthewVance I stripped the [/etc/unbound/unbound.conf] file back until the unbound container started up without error.
I also simplified the shell script I use to run the unbound container.  So far, the Unbound container is staying alive in Docker, although I don't think it is doing it's job properly.

After you confirmed that Apache Drill is available within the container, I installed the Drill package using APT outside of Docker so I could test it.
From the linux shell, If I execute 'drill www.google.com' it completes successfully, and shows that it is using 8.8.8.8 as the DNS (this is the backup DNS, it really should be using Unbound)

If I execute 'drill www.google.com @127.0.0.1' from the linux shell to force it to use unbound, it fails with the message 'Error: error sending query: Could not send or receive, because of network error'.  So I think there is still a problem with the Unbound container, but I don't know how to figure out exactly what that problem is.

I added the "--health-cmd='drill www.google.com @127.0.0.1' and the "--health-interval=5m flags in the Docker Run command to force Docker to override the HEALTHCHECK parameters in the existing container - knowing that the health would fail for me, but just to see what happened.  The Health status didn't change from 'starting' after ten minutes, so that's an interesting development.

I've attached the unbound configuration and the invocation shell script in case other readers find them useful in the future.




[unbound_conf.txt](https://github.com/MatthewVance/unbound-docker/files/12109586/unbound_conf.txt)
[docker_run_unbound_sh.txt](https://github.com/MatthewVance/unbound-docker/files/12109590/docker_run_unbound_sh.txt)

**Comment by MatthewVance** [comment]
This is a long shot, but what happens if you run dig or nslookup from another computer, pointing the IP of your Docker server? For instance, `dig google.com @192.168.1.2`. 

With it not changing from `starting', it makes me think something else is at play with your config file or run command. What is the output of Docker logs? 

Does the container work on your machine if you run with the defaults? This should help narrow down if it is an odd host networking issue or something in the custom configuration.

```
docker run \
--name=unbound-default-config \
--detach=true \
--publish=53:53/tcp \
--publish=53:53/udp \
mvance/unbound:latest
```

**Comment by DaEmbassy** [comment]
Thanks for your suggestion, @MatthewVance 
I did try 'dig google.com @192.168.1.201' from a laptop but it timed out, final message was ';; no servers could be reached'

I did try to fire up an Unbound container with the default configuration you showed - but port 53 is already reserved by the Pihole container,  and so Unbound would not start using :53, so I had to persist with publishing port 5335 for Unbound.  

When I run 'docker ps' the Unbound container shows '53/tcp, 53/udp, 0.0.0.0:5335->5335/tcp, 0.0.0.0:5335->5335/udp,  :::5335->5335/tcp, :::5335->5335/udp' whereas the ports for the Pihole container show ' 0.0.0.0:53->53/tcp, :::53->53/tcp, 0.0.0.0:53->53/udp,:::53->53/udp'

Anyway, it's more than three hours since I started the Unbound container, and it is still running and reports (healthy) status.  I did try the dig command again from my laptop, but it failed in the same way as before.

Unfortunately, the Unbound container is not taking care of DNS, and I can't see what the problem is (and neither, BTW, can my friend ChatGPT-4.  I've gone round in circles with it for days but it can't get the Unbound container to work.)

Tomorrow I think I'll re-install Ubuntu altogether, and setup pihole and unbound from bare metal again.

**Comment by MatthewVance** [comment]
Depending on your setup, it could be the firewall preventing port 5353 from being accessible from your laptop. There’s nothing wrong with bare metal either.

**Comment by DaEmbassy** [comment]
I hate not being able to solve technical problems!
I reviewed the tens of thousands of words spewed forth from ChatGPT-4 this afternoon, and realised I needed to change the settings in /etc/docker/daemon.json back to :

{
  "dns": ["<unbound-container-ip>"]
}

I did that using the Docker IP for the Unbound container, restarted Docker, and the Unbound container started doing DNS resolution.  I know that because I ran 'docker exec -it unbound /bin/sh' and entered the command in the resulting shell 'drill www.google.com @127.0.0.1', and Unbound completed the lookup in 106 milliseconds.

This was achieved running the Unbound container with the minimal settings you recommended, @MatthewVance - viz:
sudo docker run \
  --name=unbound \
  --detach=true \
  --publish=5335:5335/udp \
  --publish=5335:5335/tcp \
  mvance/unbound

What is missing from the Unbound container startup script ?
`--network=new_pihole_network` 
`--volume=/etc/unbound/unbound.conf:/opt/unbound/etc/unbound.conf`
'--volume=unbound_logs:/var/log/unbound' 
'--restart=unless-stopped' 

The critical one I want to add back is the Restart option.  I am not sure that the other three are critical if Unbound is doing DNS resolution for pihole.  What do you recommend @MatthewVance ?

**Comment by DaEmbassy** [comment]
I'm closing this ticket.

I attempted to get another Ubuntu server on my LAN to use the Unbound instance as the DNS server and it failed miserably.  I can't spend any more time trying to get unbound to work like the bare-metal version
SO
I've reinstalled Ubuntu from scratch on the server, installed Pihole and unbound bare-metal, and am getting on with life.
