### ISSUE TITLE
subnetcache warning

### ISSUE THREAD

**Issue by chris-1243** [MatthewVance/unbound-docker#139]
**Describe the bug**
Hi everyone,

I am new to unbound and the linux world.  I have just started to use this docker image via compose. Both with the original unbound.conf or the one taken to run unbound as a recurisve server, I get a warning in the logs.

Any idea how to solve this issue (if it is really one) ? I also had a try to this image: "[jedisct1/dnscrypt-server](https://github.com/DNSCrypt/dnscrypt-server-docker)" and I was not able to reproduce the warnings. 

**Error messages**
from the log:
Aug 26 18:47:40 unbound[1:0] warning: subnetcache: serve-expired is set but not working for data originating from the subnet module cache.
Aug 26 18:47:40 unbound[1:0] warning: subnetcache: prefetch is set but not working for data originating from the subnet module cache.

Many thanks for the help provided

**Comment by MatthewVance** [comment]
I'm not familiar with that one. Hopefully someone else has some ideas.

**Comment by MatthewVance** [comment]
I accidentally posted my reply before I was finished. I was also going to mention I saw a similar error in this unresolved comment https://github.com/MatthewVance/unbound-docker/issues/116#issuecomment-1703304655 for an UNRAID setup.

**Comment by nillebor** [comment]
Comment or disable in unbound.conf: `prefetch` (line 173) and `serve-expired` (line 183). 
After that, the subnetcache warning is gone.

![grafik](https://github.com/MatthewVance/unbound-docker/assets/59985723/104ea6d0-fc5a-4258-b1c9-18124a6a19cc)
