### ISSUE TITLE
configure as hyperlocal

### ISSUE THREAD

**Issue by Ghost108** [MatthewVance/unbound-docker#143]
**Describe the solution you'd like**
I would like to configure unbound as a hyperlocal solution, but I cant find a "how to" in the documentation

**Comment by MatthewVance** [comment]
While Hyperlocal is an interesting concept, but it's not one I've explored in detail. The standard caching has been sufficient for me.

Unbound is very customizable. Writing a "how to" for each possible use case is not possible. Instead, the ReadMe for this image provides generic instructions on how to load your own custom configurations. This is the method to implement the hyperlocal concept or any other special case.  

The official Unbound documentation takes a similar approach. It provides the generic instructions and high level examples, but it is up to each user to translate them into their own niche use case if the defaults are not sufficient. 

Internet forums and similar sites may also be useful for further examples.
