### ISSUE TITLE
Logging config parameter have no effects?

### ISSUE THREAD

**Issue by sadden3194** [MatthewVance/unbound-docker#144]
**Describe the bug**
I configured the highest log level but I see only a "simple log"

**To Reproduce**
1. Docker run command like yor installation guide
These are the paramter in the unbound.conf:

```
# Do not print log lines to inform about local zone actions
    log-local-actions: yes

    # Do not print one line per query to the log
    log-queries: yes

    # Do not print one line per reply to the log
    log-replies: yes

    # Do not print log lines that say why queries return SERVFAIL to clients
    log-servfail: yes

    # Set logging level
    # Level 0: No verbosity, only errors.
    # Level 1: Gives operational information.
    # Level 2: Gives detailed operational information including short information per query.
    # Level 3: Gives query level information, output per query.
    # Level 4:  Gives algorithm level information.
    # Level 5: Logs client identification for cache misses.
    verbosity: 5
```

test a query:
`dig google.de @IP_UNBOUND -p UNBOUND_PORT`

Container logs:
![Bildschirmfoto 2023-10-06 um 09 31 24](https://github.com/MatthewVance/unbound-docker/assets/17011498/1ebef561-d100-457b-80ea-8013bd7d4a67)

**Comment by MatthewVance** [comment]
Did you configure the logfile setting and account for chroot?

**Comment by Ghost108** [comment]
I am only configure the logging settings above

**Comment by MatthewVance** [comment]
I noticed the other issue you opened showed detailed logs. It appears to be having an effect. On Oct 6, 2023, at 6:33 AM, Ghost108 ***@***.***> wrote:﻿
I am only configure the logging settings above

**Comment by Ghost108** [comment]
yes but only in the logfiles. but not in the logs which I can see in the synology container manager

**Comment by MatthewVance** [comment]
That sounds like a synology or local Docker install/configuration issue. On Oct 6, 2023, at 6:40 AM, Ghost108 ***@***.***> wrote:﻿
yes but only in the logfiles. but not in the logs which I can see in the synology container manager
