### ISSUE TITLE
Disable Healthcheck

### ISSUE THREAD

**Issue by Ghost108** [MatthewVance/unbound-docker#148]
**Is your feature request related to a problem? Please describe.**
I would like to disable the health check of unbound which sends every 30 seconds a request to cloudflare

I have reinstalled the container with the parameter --no-healthcheck but withou effect.
the request still comes

```
docker run -d --name=unbound \
--no-healthcheck \
--publish=5335:53/tcp \
--publish=5335:53/udp \
--restart=always \
--net=host \
-v /volume1/docker/unbound:/opt/unbound/etc/unbound:rw \
mvance/unbound:latest
```

**Comment by MatthewVance** [comment]
Docker ignoring the no-healthcheck flag is not an issue with this container. I do not plan to disable the health check globally.

I recommend consulting Docker docs for other options:
https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
https://docs.docker.com/engine/reference/builder/#healthcheck
