### ISSUE TITLE
unbound2018-12-22 exited with code 139 / solved

### ISSUE THREAD

**Issue by hanscees** [MatthewVance/unbound-docker#149]
**Describe the bug**
when starting up docker container it wqould fail with 
`unbound2018-12-22 exited with code 139`

**To Reproduce**
1. docker-compose-up

**Expected behavior**
dns works

**Error messages**
unbound2018-12-22 exited with code 139

**Additional context**

Hi, this problem is solved, just adding ti so someone who gets the same may find the solution. 

I solved this problem by updating the unbound version in the docker container. 

In my docker-compose.yml 

`changed 
    image: mvance/unbound:1.8.3
        container_name: unbound2018-12-22`

to 
`    image: mvance/unbound:latest
Last login: Sun Oct 22 18:50:33 2023 from 192.168.0.2
`

All works fine again, but the error was a bit spooky. I think the glibc libs of the host and the container were different of something. 
To be fair, the dns container was 4 years old.

**Comment by MatthewVance** [comment]
Thanks for sharing this.
