### ISSUE TITLE
IPv6 by default not enabled

### ISSUE THREAD

**Issue by imp1sh** [MatthewVance/unbound-docker#150]
The default configuration only listens on 0.0.0.0 thus not serving IPv6 requests at all.
Please fix this bug.

**Comment by MatthewVance** [comment]
IPv6 is off by default on purpose. This is not something I have any plans to change. The image supports custom configurations for those who do not like the defaults.

https://github.com/MatthewVance/unbound-docker-rpi/issues/12#issuecomment-790246833

**Comment by imp1sh** [comment]
Would you  care to explain why that is your _default_?

**Comment by MatthewVance** [comment]
I'm not trying to be difficult, but supporting this project is already more than I keep up with. Adding further complexity to the default configuration is not something I want to do. Docker with IPv6 is tricky, so I default it to off for broader compatibility. For instance, the [Docker docs](https://docs.docker.com/config/daemon/ipv6/) say "Before you can use IPv6 in Docker containers, you need to enable IPv6 support in the Docker daemon." I do not see a major issue with it not defaulting to listen on IPv6. The default still gracefully handles IPv6 resolution.

**Comment by imp1sh** [comment]
Docker and IPv6 is horrible, I know. That's why I use podman. It just works.
Normally when you listen to "::" instead of "0.0.0.0" it will lead to answering both v4 and v6 but I cannot test if it would lead to unbound using v6 as default for querying himself, which *could* lead to problems.
Maybe you can - when you happen to build a new container - swiftly check that.
