### ISSUE TITLE
Required options in unbound.conf

### ISSUE THREAD

**Issue by fjfinch** [MatthewVance/unbound-docker#151]
First of all, thank you for the amazing image.

Just curious, what do you think are 'required' options in the unbound.conf file for your image. No matter the use case (DoT/recursive/etc), what should always be there? For example, the interface and port would be a requirement. And the username, should be in my opinion, also always be set. But then; will do-daemonize be an issue, if it's set to 'yes' (or not used)? Or what about directory/chroot if not used. These are just examples. Am curious what you think about this.

If the GitHub issue is not created correctly, or if I overlooked something; let me know.

**Comment by MatthewVance** [comment]
I don't have a list of must have options. It's not something I've thought about before. For the most part, the defaults Unbound uses when no options are set are reasonable. I think you named the main ones that are worth always setting.

You can see what I selected as default to ship with this image starting at https://github.com/MatthewVance/unbound-docker/blob/ee41830daf5906f786e0fedd153c2f440bacd8a2/1.19.0/data/unbound.sh#L41 That's for a forwarding use case. If you want to see my recursive example, look at https://github.com/MatthewVance/unbound-docker/issues/120#issuecomment-1363477286. You'll notice a lot of similarities between the two.

Depending on your network setup, `interface` may be critical (like you highlighted). 

`do-daemonize` is another critical one. The Unbound default is "yes" but "no" is a better choice when running as a container. 

Whether `chroot` and `directory` are critical is debatable. I think you could work around not using the provided settings if you account for a different directory path when mounting volumes and such. The one potential gotcha is the default exec command at: https://github.com/MatthewVance/unbound-docker/blob/ee41830daf5906f786e0fedd153c2f440bacd8a2/1.19.0/data/unbound.sh#L401 For ease of use and alignment with README examples, those would be helpful to keep.
