### ISSUE TITLE
Issue with mounting volumes

### ISSUE THREAD

**Issue by CloudEric** [MatthewVance/unbound-docker#16]
Hi I wanted to see if I could get some advice on how to mount volumes with this container as I want to try using unbound as a resolver. I'm seeing an issue with running a simple docker command.

`docker run -d --name unbound -v /mnt/dockershare/unbound/:/opt/unbound/etc/unbound/ --restart=unless-stopped mvance/unbound`

The volume is created and populated but the logs say "No such file or directory". I presume this is a permissions issue and I can see the script switch to the _unbound user. I ran the container interactively and found that the uid/pid is 1000 which is shared with my ec2-user uid/pid.

Do you have any suggestions on how to mount a volume with this container?

**Comment by MatthewVance** [comment]
Will the method detailed at
https://github.com/MatthewVance/unbound-docker/blob/master/README.md#use-a-customized-unbound-configuration
work for you?

**Comment by CloudEric** [comment]
Thanks for your response. It turns out the issue is a-records.conf was missing from my bind mount. I was testing a way to fix this but ultimately I decided use a docker container that defaults to a resolver.

**Comment by MatthewVance** [comment]
Thanks for letting me know. Glad you found an easier solution for your needs.
