### ISSUE TITLE
Documentation > Override default forward: port configuration missing when using TLS

### ISSUE THREAD

**Issue by cmonty14** [MatthewVance/unbound-docker#160]
Hi,
in the documentation [Override default forward](https://github.com/MatthewVance/unbound-docker?tab=readme-ov-file#override-default-forward) you provide an example for using TLS, however the relevant `docker run` command does not include required port 853:
```
docker run \
--name my-unbound \
--detach=true \
--publish=53:53/tcp \
--publish=53:53/udp \
--restart=unless-stopped \
---volume $(pwd)/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf:ro \
mvance/unbound:latest
```

Imo TLS will only work if port 853 is included.

Regards
Thomas

**Comment by MatthewVance** [comment]
Hi Thomas, I think it is a misunderstanding. The default is for Unbound to be a forwarding service, not a recursive DNS server. Basically, your clients talks to the Unbound DNS server over 53 and Unbound forwards the requests to another DNS server over 853. Unbound doesn't need to listen or expose 853 to reach out to another server on the Internet. You LAN traffic to Unbound would be in the clear, but Unbound would make encrypted requests to other DNS servers (meaning queries over the Internet would be protected).

**Comment by cmonty14** [comment]
Thanks for clarification.
After removing port 853 from container all DNSSEC checks confirm that _Unbound_ is working as expected.

**Comment by MatthewVance** [comment]
You might find the following visuals under the deployment section at https://www.dnscrypt.org/ helpful. This is not a 1 to 1 as DNSCrypt is different, but it may help you think through how the traffic flows can work. What I described above is similar to the visual under "Or if you totally trust the local network, the DNSCrypt client can run on the router instead:"
