### ISSUE TITLE
Docker update to unbound 1.9.2

### ISSUE THREAD

**Issue by mxmartins** [MatthewVance/unbound-docker#19]
A new version of unbound (1.9.2) came out about a week ago.  When you get a chance, can you please upload a new image into Docker?

Thanks...

**Comment by MatthewVance** [comment]
Will do.

**Comment by MatthewVance** [comment]
Updated image pushed. Thanks to @mr-bolle for submitting the 1.9.2 pull request. 

I need to check why I didn't receive an alert for this release.
