### ISSUE TITLE
Change on default access-control ( RFC 6598 )

### ISSUE THREAD

**Issue by elizandropacheco** [MatthewVance/unbound-docker#20]
Please, add the prefix 100.64.0.0/10 on unbound.conf, section access-control, accourding with RFC 6598.

This prefix is private, used on CGNAT.

Tkz.

Pachecão.

**Comment by MatthewVance** [comment]
Hi Pachecão,

Please see the discussion at
https://github.com/MatthewVance/unbound-docker/issues/10#issuecomment-456994683
.

This is not something I plan to include in the default config. If you need
this feature for your use case, it can easily be added through the custom
config support outlined in the readme.

Thanks,
