### ISSUE TITLE
Issue with sample a-records.conf

### ISSUE THREAD

**Issue by dimkasta** [MatthewVance/unbound-docker#23]
The current a-records.conf sample does not work.

The entries have to be defined in single quotes, otherwise the container keeps restarting, throwing parsing errors.

**Comment by MatthewVance** [comment]
Can you share a copy of your `a-records.conf` file? I ask because double quotes seem to be working okay for me. Do you have &ldquo; and &rdquo; or " and "? If they're the slanted (left/right version), it may cause an issue.

**Comment by dimkasta** [comment]
Sorry I was away on vacation and just got back. I do not have the files right now, but I did not do anything special. I just copy and pasted from you example into nano

**Comment by MatthewVance** [comment]
It took me a minute to see what happened. The example in the [README.md](https://github.com/MatthewVance/unbound-docker/blob/master/README.md) had the wrong type of quote in it, but the [example file](https://github.com/MatthewVance/unbound-docker/blob/master/1.9.2/a-records.conf) included with the source code was correct. I've corrected it. Thanks for reporting.
