### ISSUE TITLE
DNSSEC issues

### ISSUE THREAD

**Issue by bruvv** [MatthewVance/unbound-docker#27]
When checking if DNSSEC is working here: http://dnssec.vs.uni-due.de/ it shows that it isn't

Acording to here: https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378/2 you should disable ```use-caps-for-id``` to: ```no```
(also in the official documentation for pihole: https://docs.pi-hole.net/guides/unbound/)

**Comment by bruvv** [comment]
To add to this: I used the wrong ip when reconfiguring not it works neather the less this option is on or off. So perhaps close this but the information could be usefull that's why I am not closing it.

**Comment by MatthewVance** [comment]
I need to look into this one closer. In the interim, you may benefit from
this old thread from another user interested in Pi-Hole:
https://github.com/MatthewVance/unbound-docker/issues/21

**Comment by bruvv** [comment]
I successfully passed my own config to the docker without any issues ;)

**Comment by MatthewVance** [comment]
That's great. To confirm, DNSSEC is working for you now? The suggestion is still to consider setting `use-caps-for-id` to `no`? 

Having it set to `yes` is arguably more secure (it uses 0x20-encoded  random bits in the query to foil spoof attempts). However, I think it has caused some issues in the past. I also believe Unbound still considers this an experimental implementation of draft dns-0x20. 

As long as leaving it as `yes` isn't causing any major issues, I'd prefer to keep it that way.

**Comment by bruvv** [comment]
You're right. It is working now with the default config you provided so with the option to yes ;)

**Comment by MatthewVance** [comment]
That's great

> I successfully passed my own config to the docker without any issues ;)

That's great!
