### ISSUE TITLE
no GOST support?

### ISSUE THREAD

**Issue by bruvv** [MatthewVance/unbound-docker#29]
Sorry for the "issues" spam ;)
But when testing for GOST support (https://rootcanary.org/test.html) it fails.
![image](https://user-images.githubusercontent.com/3063928/66780111-49c89080-eed0-11e9-96f4-868cfc14f396.png)

To link: https://github.com/NLnetLabs/unbound/issues/92

**Comment by MatthewVance** [comment]
No worries. I appreciate it when people test and report potential issues.
For this particular one, I have no plans to resolve the issue. Not
supporting GOST is a good thing from my perspective.

See the Cryptanalysis of GOST section at
https://en.wikipedia.org/wiki/GOST_(block_cipher).

**Comment by bruvv** [comment]
So much knowledge thanks for sharing will close this one too!

**Comment by CumpsD** [comment]
@bruvv what does your config look like?

I was wondering if it's a good thing or not to see my current version not support DSA, DSA-NSEC3-SHA1 and ED448

![image](https://user-images.githubusercontent.com/1201644/230799599-667309fe-5c86-4d8a-853f-56ed1b206c07.png)

**Comment by MatthewVance** [comment]
For what it’s worth, my results look the same as yours. On Apr 9, 2023, at 5:34 PM, David Cumps ***@***.***> wrote:﻿
@bruvv what does your config look like?
I was wondering if it's a good thing or not to see my current version not support DSA, DSA-NSEC3-SHA1 and ED448

**Comment by CumpsD** [comment]
Yeah, I realized later it was a good result, those yellow ones are not secure to trust :)
