### ISSUE TITLE
Resolve docker service ip

### ISSUE THREAD

**Issue by rs-development** [MatthewVance/unbound-docker#31]
I run the default config for a quick test if the resolver does resolve the docker services on the same net, but it does not. 

Is there a option to do so?

**Comment by MatthewVance** [comment]
Hi. I'm not sure. One question I have, what is the need for this to be part
of the default config rather than something enabled by the default support
to provide your own config? I've never tried this setup before. I'm
wondering if you'd be better served by CoreDNS.

**Comment by rs-development** [comment]
Naah it does not need to be in the default config, i just assumed that the resolver will use the local 127.0.0.1 dns server to resolve all request, which would include the other container ips.

I have never worked with unbound, but from the config it seems that all requests are forwarded to the cloudflare dns servers.

    forward-zone:
        # Forward all queries (except those in cache and local zone) to
        # upstream recursive servers
        name: "."
        # Queries to this forward zone use TLS
        forward-tls-upstream: yes

        # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

        # Cloudflare
        forward-addr: 1.1.1.1@853#cloudflare-dns.com
        forward-addr: 1.0.0.1@853#cloudflare-dns.com

**Comment by MatthewVance** [comment]
That's right. The default config is as a a caching forwarder rather than a
recursive resolver but it can do that as well if you revise the config. The
default config does resolve LAN domains setup in a mounted a-records file.

**Comment by rs-development** [comment]
Since I don't know all local domains, since docker services get added and removed on the fly I would like to forward all requests to the docker DNS resolver, which is located at 127.0.0.11.

From inside unbound container, it is possible to nslookup "some-ngnix"

    root@c957701a6279:/opt/unbound# nslookup some-nginx
    Server:    127.0.0.11
    Address:  127.0.0.11#53
    
    Non-authoritative answer:
    Name:  some-nginx
    Address: 10.69.0.5

So I thought about just forward all traffic to the 127.0.0.11 resolver, so I added the following to the config:

        #local dns resolver
        forward-addr: 127.0.0.11@53

        # Cloudflare
        forward-addr: 1.1.1.1@853#cloudflare-dns.com
        forward-addr: 1.0.0.1@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
        #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

But if a request for "some-Nginx" is sent to the unbound server it returns
    `** server can't find some-nginx: NXDOMAIN`

Thanks for your time, I appreciate your help! Maybe you can suggest a better/working solution.

**Comment by MatthewVance** [comment]
What you're essentially looking to do is known as service discovery.
Unbound isn't targeted towards that problem domain although it could be
configured to do that by forwarding to a container aware DNS service.
Before spending too much time on this, do check out CoreDNS. You might also
want to look into Traefic or Envoy.

With Unbound, I think you're headed down the right path with forwarding to
Docker's DNS server. You may even be able to split it into zones so Unbound
forwards only Docker related items to Docker DNS and either resolves or
forwards to a public DNS server for outbound queries.

For what it's worth, when I forward to another DNS container from with an
Unbound container, I don't use IP addresses but instead have to use
@CONTAINER_NAME@ to make it work. See
https://github.com/MatthewVance/stubby-docker/blob/master/unbound/unbound.sh
for an example. I'm not sure the same applies when forwarding to the
built-in Docker DNS service though. However, it's worth a try.

**Comment by rs-development** [comment]
Thanks for the detailed reply! I will take a look at CoreDNS.

To make clear what I was trying to do and why I can not use the default dns server on 127.0.0.11.

I have a separate docker network for testing and internal admin stuff. On this admin network a openvpn server provides access from outside. If i would like to connect to some internal stuff, i connect to the VPN Network, which is located in the docker admin network. The vpn client does not have access to the containers dns resolver, it only knows the route for the admin network range. That's why I was thinking a container acting as DNS forwarder to the containers dns could solve this. I would then push the unbound container address as dns server for the vpn client.

**Comment by MatthewVance** [comment]
Thanks for providing more details. Sorry I couldn't be of more help. It's a challenging one to replicate and I haven't tried a similar scenario before. Do let me know if you land on a solution.
