### ISSUE TITLE
Mount config folder to empty folder leads to docker issue

### ISSUE THREAD

**Issue by zilexa** [MatthewVance/unbound-docker#37]
I want to use your config file but I also like to have easy access to the file and modify it as I learn more about Unbound. 

Unfortunately, the unbound docker does not work when I load it with the following in my [docker-compose.yml](https://github.com/zilexa/Mediaserver/blob/master/pihole_docker-compose.yml). Portainer says `unhealthy`:
```
    volumes:
      - ${USERDIR}/docker/unbound:/opt/unbound/etc/unbound/
```

I double tested (removed the container/volume/image/network) with and without these two lines. Without it, all works fine. With these two lines, Unbound does not startup nicely (Unhealthy).

Simply running `sudo docker-compose -f ~/docker/docker-compose.yml up -d` after commenting it out and Unbound works fine. Uncommenting and run this command and it is unhealthy again. 

Would it be an idea to **_always_** load your config when a container is created? Users can then overwrite the file with their own OR choose to modify yours.

EDIT: some more testing with and without those two lines: 
with it, the folder`${USERDIR}/docker/unbound` is automatically created and it seems to contain your config. 

I really do not understand why unbound does not launch when I mount the above mentioned volume.

When I don't mount it, _all is fine._ `dig` says NOERROR. And all clients are able to resolve DNS requests via Unbound.

**Comment by MatthewVance** [comment]
> I really do not understand why unbound does not launch when I mount the above mentioned volume.

The [unbound.sh](https://github.com/MatthewVance/unbound-docker/blob/d3cf9d23e79245b16c6198fa29ec505330d76674/1.10.0/unbound.sh) file called by [CMD](https://github.com/MatthewVance/unbound-docker/blob/d3cf9d23e79245b16c6198fa29ec505330d76674/1.10.0/Dockerfile#L143) is used during the initial container start. It's designed to optimize the performance related settings in the default unbound.conf file to match the machine it's being run on. This [pull request](https://github.com/MatthewVance/unbound-docker/pull/2) may also help explain.

Always loading my config and allowing user to overwrite it could work. I prefer not to take that approach. I'm concerned it could create some unexpected results for people who may want to use multiple config files. 

If you mount a volume to the unbound directory, the container assumes the user will provide properly configured config files. If you only want to provide a single file such as a-records.conf and still use the default config, the current setup should support that if you run it like:  
```
docker run --name my-unbound -d -p 53:53/udp -v \
$(pwd)/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro \
--restart=always mvance/unbound:latest
```

If it helps, [here's](https://gist.github.com/MatthewVance/4842e0ad8305a09e87b95787e656243d) what the auto-generated config looks like by default (performance settings are auto-tuned by the unbound.sh launch script and these are from a container running on an under-powered VM so keep that in mind).

Does this help explain what's going on behind the scenes and leading to the behavior you're seeing?
