### ISSUE TITLE
proposal: place forward record in a dedicated file like "a" records

### ISSUE THREAD

**Issue by Sispheor** [MatthewVance/unbound-docker#40]
So the file can be overridden .

In the unbound.conf:
```
include: /opt/unbound/etc/unbound/forward-records.conf
```

Because so far if we want to override only this part to provide company DNS we need to override the whole unbound.conf file.

**Comment by MatthewVance** [comment]
That's a good idea. Do you want to submit a pull request for this
enhancement?

**Comment by MatthewVance** [comment]
Closed by PR #41
