### ISSUE TITLE
Probing cloudflare every 5 seconds

### ISSUE THREAD

**Issue by CodeSapiens** [MatthewVance/unbound-docker#44]
Hello and thanks for providing your code free.
I have been racking my brain trying to figure out why all of a sudden my Pihole is pinging cloudflare every 5 seconds, and it appears your container code is doing it. As soon as I shut it down, the pinging stops.
I have other installs of Unbound that don't do that, so I am guessing this is something you added. Could you please point me to where I can disable that? I don't want those queries, and certainly not at that rate. I have other ways to test connectivity.

One more thing, side issue. The local-data entries don't seem to work with the current set of options. No resolution is passed onto my network devices from the list I entered, following carefully the correct syntax.

Thanks!

**Comment by MatthewVance** [comment]
For the Cloudflare probe, see
https://github.com/MatthewVance/unbound-docker/issues/25. To disable,
comment out the docker health check line and re-build the image or run it
with the no-healthcheck flag.
https://docs.docker.com/engine/reference/run/#healthcheck

For the other question, can you provide more context and detail?

**Comment by CodeSapiens** [comment]
Thank you much for the quick reply. I will check that healthcheck setting, and give my hard drives a breather. :-)

The local resolution issue, I'm guessing it may have to do with the fact that I am forwarding my queries, which probably makes Unbound a non-authoritative resolver?

Here are my forward settings:
forward-zone:
    name: "."
    forward-tls-upstream: yes

    forward-addr: 1.1.1.2@853           # Cloudflare Security
    forward-addr: 185.228.168.9@853     # CleanBrowsing Security
    forward-addr: 9.9.9.9@853           # Quad9 1 Security
    forward-addr: 149.112.112.112@853   # Quad9 2 Security
    forward-addr: 45.90.28.0@853        # NextDNS 1 Security
    forward-addr: 45.90.30.0@853        # NextDNS 2 Security
    forward-addr: 176.103.130.130@853   # AdGuard Security

Here are some of my local entries (changed names to protect the innocent):
local-zone: "mycustomdomain.com." static

# A Record
local-data: "pc1.mycustomdomain.com. IN A 10.30.15.2"
local-data: "pc2.mycustomdomain.com. IN A 10.30.15.5"

# PTR Record
local-data-ptr: "10.30.15.2 pc1.mycustomdomain.com."
local-data-ptr: "10.30.15.5 pc2.mycustomdomain.com."

All other settings are pretty much what your template includes.
When I try to ping or nslookup any of those records, the A record is non existent, and the PTR returns the hardware based host name. So resolution is ignoring those entries. Not sure what I am missing. I don't want to deploy a full blown DNS server if I can avoid it.

Thanks in advance for your time!
Jul 7, 2020, 11:06 AM by notifications@github.com:

>
>
>
> For the Cloudflare probe, see
>  https://github.com/MatthewVance/unbound-docker/issues/25. To disable,
>  comment out the docker health check line and re-build the image or run it
>  with the no-healthcheck flag.
>  https://docs.docker.com/engine/reference/run/#healthcheck
>  
>  For the other question, can you provide more context and detail?
>

**Comment by CodeSapiens** [comment]
Please pardon my ignorance, but how do I get to the file I need to edit to disable the healthcheck?
I am running Docker in a Synology NAS, which only shows me the nice interface to control the containers and images, but I am not sure where the files are. Or is there a setting I can add to my unbound.conf to override the healthcheck?

Thanks!

Jul 7, 2020, 11:06 AM by notifications@github.com:

>
>
>
> For the Cloudflare probe, see
>  https://github.com/MatthewVance/unbound-docker/issues/25. To disable,
>  comment out the docker health check line and re-build the image or run it
>  with the no-healthcheck flag.
>  https://docs.docker.com/engine/reference/run/#healthcheck
>  
>  For the other question, can you provide more context and detail?
>

**Comment by MatthewVance** [comment]
The healthcheck is a Docker thing, not an Unbound setting so the conf file
won't help.

I am not familiar with that NAS so I won't be able to provide detailed
help. Your options may be limited if you're restricted to a GUI. Normally,
you'd add that option as a docker run flag when launching via a command
line interface. Using the generic launch method, it would look something
like this:

docker run --name my-unbound -d -p 53:53/udp -p 53:53/tcp \
--no-healthcheck \
--restart=always mvance/unbound:latest

You could also try converting to a docker-compose file if your NAS supports
that.  I believe you can also disable Docker healthchecks that way.

**Comment by CodeSapiens** [comment]
I will look into that. Thanks.

Jul 7, 2020, 11:41 AM by notifications@github.com:

>
>
>
> The healthcheck is a Docker thing, not an Unbound setting so the conf file
>  won't help.
>  
>  I am not familiar with that NAS so I won't be able to provide detailed
>  help. Your options may be limited if you're restricted to a GUI. Normally,
>  you'd add that option as a docker run flag when launching via a command
>  line interface. Using the generic launch method, it would look something
>  like this:
>  
>  docker run --name my-unbound -d -p 53:53/udp -p 53:53/tcp \
>  --no-healthcheck \
>  --restart=always mvance/unbound:latest
>  
>  You could also try converting to a docker-compose file if your NAS supports
>  that.  I believe you can also disable Docker healthchecks that way.
>

**Comment by MatthewVance** [comment]
How you doing on this? You had two main questions and I only addressed one of them. Do you still need help on this? Trying to catch back up on GitHub after taking a break for a bit.

**Comment by CodeSapiens** [comment]
I'm good now. Thank you for following up.

Jul 28, 2020, 9:51 PM by notifications@github.com:

**Comment by ilium007** [comment]
In case anyone else stumbles across this like I did tonight... I am running this unbound container with custom config on port 5353 and needed to change the health check in my docker-compose.yml to support the port 5353 check:

```
healthcheck:
      test: drill @127.0.0.1 -p 5353 cloudflare.com || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
```

**Comment by MatthewVance** [comment]
Thanks for sharing.
