### ISSUE TITLE
Boot loop: Cannot start container on Docker for Windows due to lack of dev/random and /dev/urandom

### ISSUE THREAD

**Issue by rafaelreis-r** [MatthewVance/unbound-docker#45]
Hey there!

I tried running the container on Docker for Windows. I was able to mount the volume for unbound.conf. Successfully edited it. But I cannot start the container due to the following error:

```cp: cannot create special file '/opt/unbound/etc/unbound/dev/random': Input/output error```

```cp: cannot create special file '/opt/unbound/etc/unbound/dev/urandom': Input/output error```

For me it seems that the container image relies on a unix host to provide /dev/random and /dev/urandom, which is not available on Docker for Windows. I'm not using Windows containers, just Linux containers, however it seems the that for this specific unbound Docker image some tweaking might be required to avoid that error. 

For information, I have many other linux images deployed on my Windows host with no issues.

**Comment by MatthewVance** [comment]
Thanks for reporting this. I need to look into this more. There's a dev/null [pull request / issue](https://github.com/MatthewVance/unbound-docker/pull/32) I've been needing to look into further. I'm thinking this may be related. Once I resolve that, I'll need help testing on Docker for Windows.

**Comment by MatthewVance** [comment]
I've pushed the change to unbound:latest. Please let me know if that helped with the issue.

**Comment by rafaelreis-r** [comment]
Hey thanks for the update!

It was a bit challenging to get it to work with a custom config since the container tty output is very minimal and hard to debug with. I ended up generating and testing a config on a linux host bare metal install, then moving the config to windows docker volume mount. 

Tested on: 

![image](https://user-images.githubusercontent.com/57492577/89789522-15752f00-daf7-11ea-8774-1faa154a959f.png)

Windows Engine (WSL disabled)

Container starts, runs fine, responds do dig requests, responds to a neighbouring pihole container on the same docker network. 

Seems to be 100%. As an improvement suggestion, I'd make the container console verbosity higher. 

Thanks!

**Comment by MatthewVance** [comment]
Thank you for testing and confirming. I hear your point about the container console verbosity. It's largely a tradeoff I made to have a fairly secure and privacy conscious default config. 

The logging section of the unbound.conf (generate by unbound.sh) pretty much turns off all logging output. The `logfile: /dev/null` was the source of the issue you had with Windows. I needed to update the `CP` command to make `/dev/null` available within the chroot directory (/opt/unbound/etc/unbound).

```
    ###########################################################################
    # LOGGING
    ###########################################################################
    # Do not print log lines to inform about local zone actions
    log-local-actions: no
    # Do not print one line per query to the log
    log-queries: no
    # Do not print one line per reply to the log
    log-replies: no
    # Do not print log lines that say why queries return SERVFAIL to clients
    log-servfail: no
    # Further limit logging
    logfile: /dev/null
    # Only log errors
    verbosity: 0
```
