### ISSUE TITLE
[question] expand this docker to include adblocking

### ISSUE THREAD

**Issue by zilexa** [MatthewVance/unbound-docker#48]
I recently became a bit disgruntled with my Unbound + PiHole combination. 
PiHole is there for adblocking, but does not provide a way to quickly and easily disable adblocking for a specific IP (device). It also seems development is not focused on supporting that. 
It has nice stats and visuals, but they are empty/useless in my case because I don't allow PiHole to store the data of all clients. I consider that should remain private. So basically PiHole does not offer me anything Unbound cannot do as well, since the PiHole UI is simply not very useful and I do not use it at all. It also makes my whole setup unnecessarily complex.

I found this information, it allows to add an ablocking list and - a big plus over PiHole - forward ad/tracking requests to a 1x1 pixel (running a tiny pixelserver) so that you won't see ugly errors where an ad should load on some websites:
https://etherarp.net/build-an-adblocking-dns-server.html
How amazing is that? 

Now my question is if you like the information on that site and are willing to make a few changes, so that your Unbound also enables caching and especially the script the writer wrote to convert ad blocking hosts files to something Unbound can use: 
https://github.com/rohan-molloy/unbound-adblock
And perhaps (I know I am going a bit far here) include the whole solution as optional via docker compose, including the IP override/pixel server solution?

**Comment by MatthewVance** [comment]
Hi @zilexa. Thanks for the suggestion. This isn't something I plan to implement though. 

Adblocking is outside the core purpose for this project. The intent is to provide a generic Unbound image that has reasonably secure defaults for a forwarding to an upstream resolver over TLS, but be flexible enough to support custom configurations to meet other needs. 

You're more than welcome load your own config when launching the container or fork this repo to implement your above idea. If you decide to implement this, take a look at [Caddy](https://caddyserver.com/) in lieu of lighttpd for the tiny pixelserver.

By the way, the default config already enables caching.
