### ISSUE TITLE
Docker Hub Image Broken

### ISSUE THREAD

**Issue by sammerry** [MatthewVance/unbound-docker#5]
The docker hub image is broken. The white space in unbound.sh causes it to ignore the `fi` at the end of the file and wont run without replacing it.

**Comment by Gymnae** [comment]
Also facing this problem now.

**Comment by MatthewVance** [comment]
Thanks for the report. I'll fix when I can. In the interim, you can build
the image manually if needed.

**Comment by MatthewVance** [comment]
New images are building now. I built and tested locally with 1.8.1 to confirm the fix.
