### ISSUE TITLE
Unbound fails to start

### ISSUE THREAD

**Issue by vidurb** [MatthewVance/unbound-docker#52]
Hi, 
I just pulled the latest image and restarted my local stack and noticed that the `unbound` container was constantly restarting. I found the following error in the logs, which seems like an error in the container build to my eyes, but I defer to your superior knowledge:
```
unbound    | /opt/unbound/sbin/unbound-anchor: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory
unbound    | /opt/unbound/sbin/unbound: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory
```

Edit: I see this is likely linked to your latest feature addition (DoH). Apologies if I'm doing something wrong and this is expected behaviour.

Edit2: I'm running Docker version 19.03.8 on 5.4.0-48-generic kernel (Ubuntu 20.04.1)

**Comment by vidurb** [comment]
I switched to the `1.12.0` tag from `latest`, and that tag is working fine, for anyone else who chances upon this via search and wants to get their DNS back up quick.

**Comment by norrisp90** [comment]
+1. I'm experiancing the same issue.

I'm running the contianer in Docker 19.03.5 on Linux 4.19.107-Unraid x86_64.

**Comment by MatthewVance** [comment]
My apologies. Latest should be working again.

**Comment by vidurb** [comment]
No problem at all. Your contribution to the community is much appreciated,
and I laud you for your quick support.

**Comment by MatthewVance** [comment]
@vidurb thank you. Much appreciated. 

The image size is now a bit bigger than I like though so I may if I can find an easy way to reduce it while maintaining the components necessary to support DoH usages for those who want to run this image with that type of configuration. I haven't played with it yet, but I'd like to.

https://medium.com/nlnetlabs/dns-over-https-in-unbound-c7a407e8480
