### ISSUE TITLE
Address not found via Unbound, found if bypassing Unbound

### ISSUE THREAD

**Issue by zilexa** [MatthewVance/unbound-docker#53]
Using the default config, I get "Address Not Found" when accessing this site:
`https://p.notificatie.postnl.nl`

However when I switch my Unbound IP for 1.1.1.1 in my router, I can access the site just fine (forwards to `https://jouw.postnl.nl`)

I believe Unbound uses 1.1.1.1 as upstream by default. This means something is going wrong when processed by Unbound. What could it be?

**Comment by MatthewVance** [comment]
That's odd. Default forward-zone file includes CleanBrowsing Security
Filter in addition to Cloudflare. Does it work if you comment that one out?
You'd run everything as default still, except you would need to manually
mount the forward-zone file as a volume?

**Comment by zilexa** [comment]
I cannot test this now, will do it this weekend, sorry, didn't expect such a quick reply!

**Comment by zilexa** [comment]
I did it anyway (studying for a major test..). And that solved it: 

```
    ## CleanBrowsing Security Filter
    # forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
    # forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
```

**Comment by MatthewVance** [comment]
No worries. I'm not able to test right away either.

**Comment by MatthewVance** [comment]
Great. I need to comment that config out in a future update.

**Comment by zilexa** [comment]
Thanks for the quick help and solution!

btw perhaps in addition to the other (commented out) options, consider adding Adguard DNS in there? 
Source (scroll halfway): https://adguard.com/en/adguard-dns/overview.html

```
IPv4
Filtered  "Default" servers:
94.140.14.14
94.140.15.15
Filtered "Family protection" servers:
94.140.14.15
94.140.15.16

IPv6
Filtered "Default" servers:
2a10:50c0::ad1:ff
2a10:50c0::ad2:ff
Filtered "Family protection" servers:
2a10:50c0::bad1:ff
2a10:50c0::bad2:ff

Please note: the "Non-filtering" DNS servers provide a secure and reliable connection, but they don't filter anything like the "Default" and "Family protection" servers do. Please don't use them unless you know what you're doing:

IPv4
For "Non-filtering":
94.140.14.140
94.140.14.141

IPv6
For "Non-filtering":
2a10:50c0::1:ff
2a10:50c0::2:ff
```
