### ISSUE TITLE
udp connect failed

### ISSUE THREAD

**Issue by MatthewVance** [MatthewVance/unbound-docker#55]
I build 1.13 at my Server  but dont work. also klutchell/unbound dont work it has the same error.
and Pihole can't connect on unbound. Reinstall Matthews Version and all are running fine.
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
[1607543446] libunbound[47:0] error: udp connect failed: Address not available for 2001:500:a8::e port 53

_Originally posted by @beroliv in https://github.com/MatthewVance/unbound-docker/issues/54#issuecomment-742021796_

**Comment by MatthewVance** [comment]
The IPv6 addresses in the error appear to be associated with root servers: https://www.iana.org/domains/root/servers

**Comment by MatthewVance** [comment]
Continuing to research. This may be related to https://github.com/NLnetLabs/unbound/issues/364.

**Comment by mxmartins** [comment]
I have a raspberry pi running 1.13.0 and I am not seeing any of those issues. 
I also have a docker container running 1.12.0 and no issues noted as well.....

On both systems, the unbound.conf is properly setup to handle IPv6 upstream and downstream...

Possibly check you unbound.conf settings, here are mine as they pertain to IPv6
# Listen to for queries from clients and answer from this network interface
    # and port.
    interface: 0.0.0.0@53
	interface: ::@53
	
# May be set to yes if you have IPv6 connectivity
	do-ip6: yes
	
# Only give access to recursion clients from LAN IPs	
access-control: 2xxx:xxxx:xxxx:ee21::0/64 allow

# These private network addresses are not allowed to be returned for public
    # internet names. Any  occurrence of such addresses are removed from DNS
    # answers. Additionally, the DNSSEC validator may mark the  answers  bogus.
    # This  protects  against DNS  Rebinding
    private-address: 2xxx:xxxx:xxxx:ee20::/60

**Comment by mxmartins** [comment]
Just saw this as I was digging around.....  

https://github.com/NLnetLabs/unbound/issues/364

https://forums.freebsd.org/threads/libunbound-error.78121/

**Comment by MatthewVance** [comment]
Thanks for sharing. I hadn't seen the forum post yet. I think that is the
same upstream  issue I found.

**Comment by dannytsang** [comment]
I'm seeing similar errors all looking like IPv6 related.

**Comment by MatthewVance** [comment]
This will hopefully be fixed in the next release of Unbound. A fix appears
to have been merged into the main branch:
https://github.com/NLnetLabs/unbound/commit/08968baec1122a58bb90d8f97ad948a75f8a5d69

**Comment by MatthewVance** [comment]
Closing this because this is an upstream issue.

**Comment by MatthewVance** [comment]
Fix #358 in 1.13.1 should address this: https://nlnetlabs.nl/projects/unbound/download/#unbound-1-13-1

**Comment by ajostergaard** [comment]
Hello - I seem to have this issue with this container and as described in [](https://github.com/MatthewVance/unbound-docker-rpi/issues/12) it stops Unbound from starting at all. Any suggestions for a workaround while a fix is underway? Would it be possible to re-open this issue or shall I monitor the other issue instead.

**Comment by ajostergaard** [comment]
You are right. :) I found my stupid error - sorry! Left the A out of my A records... DUH. :-/

**Comment by MatthewVance** [comment]
No worries. It happens to the best of us.

It's common enough I should probably work on improving the readme.
