### ISSUE TITLE
Startup script does not appropriately limit memory to cgroups limitations

### ISSUE THREAD

**Issue by apschultz** [MatthewVance/unbound-docker#56]
It is pretty common on shared systems to limit the amount of memory available to containers. If the memory allowed for the containers is very small compared to overall memory, things will misbehave. In my case, the container pretty much stopped functioning entirely until it was reset.

> root@stubby-unbound:/opt/unbound# cat /proc/meminfo
> MemTotal:        7989764 kB
> MemFree:         1706884 kB
> MemAvailable:    5329184 kB
> 
> root@stubby-unbound:/opt/unbound# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
> 209715200

unbound.sh could easily check the cgroup memory limits (if available) or possibly use an environment variable to be set for broader compatibility.

**Comment by MatthewVance** [comment]
Feel free to submit a pull request with the enhancement.

**Comment by MatthewVance** [comment]
Adam, thanks for the suggestion and PR. This will be a good enhancement.

**Comment by apschultz** [comment]
Happy to help. I'll close this issue since the PR is pending.
