### ISSUE TITLE
Unable to get container to create

### ISSUE THREAD

**Issue by snoopy82481** [MatthewVance/unbound-docker#60]
When I'm creating the container the logs are showing the following errors:
cp: cannot create special file '/opt/unbound/etc/unbound/dev/random': Operation not permitted
cp: cannot create special file '/opt/unbound/etc/unbound/dev/urandom': Operation not permitted
cp: cannot create special file '/opt/unbound/etc/unbound/dev/null': Operation not permitted
chown: changing ownership of '/opt/unbound/etc/unbound/var': Invalid argument

I am running as a privileged user so I was able to get away from the error: 
"unbound[1:0] warning: so-rcvbuf 1048576 was not granted"

I have using it in a k3s cluster and have piHole running.  I am following this deployment method: https://runf11s.com/PiHole-and-Unbound-on-k8s but with your image.

**Comment by MatthewVance** [comment]
A couple of things to note. The default config for this image runs as
_unbound as the user. It drops privileges after port binding. It also uses
chroot so that can impact path expectations.

This thread may help:
https://github.com/MatthewVance/unbound-docker/issues/21

**Comment by MatthewVance** [comment]
Also see: https://github.com/MatthewVance/unbound-docker/issues/9#issuecomment-448758929

**Comment by MatthewVance** [comment]
Closing due to no response.
