### ISSUE TITLE
Is there any way to see DNS requests coming in with default settings?

### ISSUE THREAD

**Issue by otisbison** [MatthewVance/unbound-docker#62]
This is my first time trying out docker images. Is there a reason that basically all logging is disabled by default?

I was hoping to at least see that requests were coming in, but I'm a bit reluctant to modify anything.

**Comment by MatthewVance** [comment]
Logging is disabled by default for privacy reasons. The provide config is
designed with security and privacy mind.

Logging can be enabled by mounting your own config as a volume. The default
config is generated by the unbound.sh file. It's well commented so seeing
which settings are log related should be easy.

You can also exec into the container to see the generated version and copy
it down. From there, you can modify and relaunch with the modified version
mounted as a volume.

If you need more help, let me know. Docker is cool but takes a bit of
learning.

**Comment by MatthewVance** [comment]
You can find the Privacy setting section starting at: https://github.com/MatthewVance/unbound-docker/blob/5902cff11a59283e568e3622189e676be2ac0bfc/1.13.1/unbound.sh#L108

If you're not sure how to convert that shell script to an unbound.conf file, I provide an example unbound.conf file in [this issue reply](https://github.com/MatthewVance/unbound-docker-rpi/issues/9#issuecomment-770470060) (for the Pi version, but it's basically the same).

Once you have that file (with the updated logging settings), [this walks](https://github.com/MatthewVance/unbound-docker#use-a-customized-unbound-configuration) you through how to provide and launch with a custom config file.

**Comment by otisbison** [comment]
Thanks for your help.
