### ISSUE TITLE
I saw a possibility of improvement in your dockerfile

### ISSUE THREAD

**Issue by Brettdah** [MatthewVance/unbound-docker#65]
Hello Matthew,
did you know that by reproducing the path inside the container in a folder you can just do 1 COPY instruction ?
for exemple 
instead of :
```
COPY a-records.conf /opt/unbound/etc/unbound/
COPY forward-records.conf /opt/unbound/etc/unbound/
COPY srv-records.conf /opt/unbound/etc/unbound/
COPY unbound.sh /
```

If you add a folder let's say "unbound" and put the 3 conf files in it you can do
```
COPY unbound /opt/unbound/etc/unbound/
COPY unbound.sh /
```

So now you if we just want 1 COPY instruction (i'll use linux instruction instead of explaining) :
```bash
mkdir -p ./rootfs/opt/unbound/etc/unbound/
cp unbound.sh ./rootfs/
cp *.conf ./rootfs/opt/unbound/etc/unbound/
```
so you will just have to do :
`COPY rootfs/ /`

Now if you already knew and chose to do the way you did sorry for that message ^^

regards,

Brett

**Comment by MatthewVance** [comment]
Hi Brett,

Good catch. I appreciate you sharing this. Feel free to submit a pull
request for the optimization.

Regards,
Matt

**Comment by Brettdah** [comment]
Hi Matthew,

I got it ready for 1.13.1 tested localy (through docker build)
Should I look on the other versions to apply the same modification ?

Regards,
Brett

**Comment by MatthewVance** [comment]
Hi Brett,

Your PR looks good. Thank you for contributing this optimization. It is not
necessary to backport to the other, older versions.

Thanks,
Matthew

**Comment by Brettdah** [comment]
Hi, ok no problem great to be of some help
keep up the good work...

**Comment by MatthewVance** [comment]
Closed by https://github.com/MatthewVance/unbound-docker/pull/66
