### ISSUE TITLE
Healthcheck every 5s - overkill? (constantly writing to log files)

### ISSUE THREAD

**Issue by zilexa** [MatthewVance/unbound-docker#67]
It took me a while to figure this one out, this is /var/log/syslog:

```
Jun 23 15:52:25 Obelix systemd[1465]: run-docker-runtime\x2drunc-moby-046278d6c031977c7db6c60142adb934199c71640b38b9c635a1f54f5d350151-runc.2nWGMG.mount: Succeeded.
Jun 23 15:52:25 Obelix systemd[1]: run-docker-runtime\x2drunc-moby-046278d6c031977c7db6c60142adb934199c71640b38b9c635a1f54f5d350151-runc.2nWGMG.mount: Succeeded.
Jun 23 15:52:30 Obelix systemd[1]: run-docker-runtime\x2drunc-moby-046278d6c031977c7db6c60142adb934199c71640b38b9c635a1f54f5d350151-runc.oz8Hww.mount: Succeeded.
Jun 23 15:52:30 Obelix systemd[1465]: run-docker-runtime\x2drunc-moby-046278d6c031977c7db6c60142adb934199c71640b38b9c635a1f54f5d350151-runc.oz8Hww.mount: Succeeded.
Jun 23 15:52:36 Obelix systemd[1465]: run-docker-runtime\x2drunc-moby-046278d6c031977c7db6c60142adb934199c71640b38b9c635a1f54f5d350151-runc.1uKI8V.mount: Succeeded.
```
Since there was no way to trace this to a specific container, I stopped all my containers and start/stopped them one by one. There are other containers with a health check, usually every minute. Sometimes for apps that are quite static, making it overkill.

For Unbound a healthcheck makes sense of course, but very 5sec might be a bit overkill?
If a website is inaccessible, I wouldn't immediately check Unbound status, most likely there are other causes. Perhaps 1min is enough?

**Comment by MatthewVance** [comment]
You should be able to customize it to your liking at run time:
https://docs.docker.com/engine/reference/run/#healthcheck
