### ISSUE TITLE
Trying to squeeze some more performance out of Unbound

### ISSUE THREAD

**Issue by 0ctatr0n** [MatthewVance/unbound-docker#75]
I've been having mixed results with your unbound docker instance running as dns for Pihole, videos stop and start and there's a delay of 30 seconds waiting for pages to load.

I've tweaked unbound.conf with the following:

```
#I have 2 cores
num-threads: 2

so-rcvbuf: 8m
so-sndbuf: 4m

#Bits I added to improve cache performance
cache-min-ttl: 0
serve-expired: yes
msg-cache-size: 128m
rrset-cache-size: 256m

# Slabs settings 2x number of cores
msg-cache-slabs: 4
rrset-cache-slabs: 4
infra-cache-slabs: 4
key-cache-slabs: 4

# Faster UDP with multithreading
so-reuseport: yes

# Service more client per core
outgoing-range: 450

```
However when I spin it up I get these errors in the logs:

```
warning: so-sndbuf 4194304 was not granted. Got 425984. 
warning: so-rcvbuf 8388608 was not granted. Got 425984.

To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux)
To fix: start with root permissions(linux) or sysctl bigger net.core.wmem_max(linux)
```
I tried added these settings to sysctl.conf but it still causes this error

I've looked into this and apparently if I disable "ProtectKernelTunables" it will fix the issue with increasing the send receive buffers

I cannot seem to find the unbound.service file on your docker instances.

Could you point me to where I can adjust the "ProtectKernelTunables" variable?

Alternatively do you know of a better way to allocate more memory and cpu cores to Unbound so I can stop the delays and drop outs?

**Comment by MatthewVance** [comment]
It's a Docker container so no service file is used. Performance for your
instance of this image is dependent on your hardware and what load your
placing on the running container and any other resources sharing the same
hardware.

When a custom config is used, like when used with Pi Hole setup, it is up
to you to set appropriate values. Thus may help:
https://nlnetlabs.nl/documentation/unbound/howto-optimise/

The default config auto tunes performance settings based on available
resources via the unbound.sh script. You can run it with the defaults to
get a sense of what ideal values may be by looking at what's auto generated.
https://github.com/MatthewVance/unbound-docker-rpi/blob/master/1.13.1/data/unbound.sh

Keep in mind the nuances with Docker when trying to tune the kernel.

**Comment by csousougen** [comment]
"videos stop and start" this issue doesn't seem dns related, unless the video provider has a very small TTL value.
Try "cache-min-ttl: 3600" just to see if it solves this problem.

**Comment by MatthewVance** [comment]
@0ctatr0n  I'm going to go ahead and close this one because I haven't heard back in a while and I don't think this is an issue with this image.
