### ISSUE TITLE
cachedb options

### ISSUE THREAD

**Issue by csousougen** [MatthewVance/unbound-docker#76]
cachedb options for redis backend do not work. 
Have you built Unbount with --with-libhiredis ?

**Comment by MatthewVance** [comment]
No, I have not.

You can see the build commands here:
https://github.com/MatthewVance/unbound-docker/blob/f877023af5e65922caa9430e02e2d09f7af42007/1.13.2/Dockerfile#L71

**Comment by csousougen** [comment]
Thanks for the reply. Please consider the support of redis db in order to save cache between docker restarts.

**Comment by Qeynos** [comment]
i tried to edit dockerfile with --with-libhiredis, but all failed, dont know how, but i think its useful
