### ISSUE TITLE
unbound with adguard home docker

### ISSUE THREAD

**Issue by balajeek** [MatthewVance/unbound-docker#78]
Its not at all an issue with unbound and googled a lot and still couldn't find a way.

I installed adguard home on docker and it seem work well. 
now i am unable to set unbound as a upstream dns server from setting of adguard.
I tried docker ip, 127.0.0.1 and 192.168.1.13 (where unbound is running on port 5053), it complains "Server could not be used"

![image](https://user-images.githubusercontent.com/19213088/130688805-a624aa04-f311-40a3-8b18-2ac8dd97e960.png)

Anyone done it?

FYI: I had it pi-hole before stopping it and it worked fine
![Screen Shot 2021-08-24 at 1 11 31 PM](https://user-images.githubusercontent.com/19213088/130688936-4988aa07-1242-47ba-8a3e-b71192708878.png)

**Comment by MatthewVance** [comment]
@balajeek I'm going to go ahead and close this one because I haven't heard back in a while. If the above didn't solve it for you, feel free to reopen this.
