### ISSUE TITLE
Need some troubleshooting advice

### ISSUE THREAD

**Issue by icsy7867** [MatthewVance/unbound-docker#79]
I deployed to more CoreOs docker server using the basic docker command:

docker run --name my-unbound -d -p 53:53/udp -p 53:53/tcp \
--restart=always mvance/unbound:latest

But I'm not resolving anything.  I disabled the systemd-resolver and pointed my windows VM to The docker server.  But I can't get anything to resolve.

I added a few local entries to the a-records but still not resolving.  Also tried to restart the container.

Docker logs only tell me that they couldn't bind or use some ipv6 addresses which makes sense and doesn't seem to relate.

I'm not too familiar with unbound but was just curious if anyone had any advice.  Thanks!

**Comment by icsy7867** [comment]
I think I figured it out.  I have an odd subnet, so I had to allow this in the conf under the private network section.

**Comment by MatthewVance** [comment]
Great. If you need help again, feel free to re-open this or submit a new issue.
