### ISSUE TITLE
Unbound on k3s/k8s

### ISSUE THREAD

**Issue by SchoolGuy** [MatthewVance/unbound-docker#84]
Sadly https://github.com/MatthewVance/unbound-docker/issues/60 was never finished but anyway I moved past this now.

The remaining problem is the following: I do have a custom configuration mounted as a projected volume. This means the directory `/opt/unbound/etc/unbound` becomes read-only since this is required to my understanding of projected volumes in Kubernetes.

The workaround for this which I suggest is simple: Let's create a location in the image - `/config` for example - and if there are configfiles, they get copied to the "final" location `/opt/unbound/etc/unbound`. This would be transparent as the startup script would do this on every container restart and thus an updated configuration file would be reflected on a container restart.

**Comment by SchoolGuy** [comment]
Update I solved it - I guess? - with `subPath`s in the deployment. But now I get `Error´ and I have no output. I used the following tutorial to solve my problem: https://dev.to/joshduffney/kubernetes-using-configmap-subpaths-to-mount-files-3a1i

**Comment by SchoolGuy** [comment]
Please don't close the issue yet because I do not yet have a fully working unbound running.

**Comment by SchoolGuy** [comment]
Okay the DNS container is running now. Exposing via the `svc` is not working as expected but I believe that this is purely on my side now. I will close this issue.

@MatthewVance are you interested in describing how this works in your README? If yes I would open a PR for this.

**Comment by SchoolGuy** [comment]
Okay. I have it working. The solution to make the DNS server reachable from the outside is either the `hostPort` option or an ingress which exposes that via a load balancer. I have choosen the first option since I only have one node.

**Comment by MatthewVance** [comment]
@SchoolGuy yes, I'm open to adding a section in the README to describe this. I'm glad you were able to work through this and share the solution. Thank you!

**Comment by SchoolGuy** [comment]
@MatthewVance You want a PR with my examples or you add a note yourself?

**Comment by MatthewVance** [comment]
A PR with yours would be great.
