### ISSUE TITLE
Unbound can't open log file - permission denied

### ISSUE THREAD

**Issue by nuevilly** [MatthewVance/unbound-docker#85]
Hi there,

I'm running Unbound alongside AdGuard Home in Docker on my Synology NAS.  It has been working well for the last ~12 months.

Today, I noticed that my docker logs have a couple of errors

```
[1633911210] libunbound[22:0] error: udp connect failed: Cannot assign requested address for 2001:500:a8::e port 53 | stdout

[1633911210] unbound[1:0] error: Could not open logfile /dev/null: Permission denied
```

The first of these errors (udp connect failed) has been around for a long time, and doesn't seem to be affecting performance.  The second error (could not open log file) is new.  I'm not sure what's causing this - is this normal or indicative of something going wrong?

I've also noticed today that when I run dnsleaktest.com, it shows two Cloudflare servers.  These are not my ISP's servers - I'm not sure what they are.    Previously dnsleaktest.com showed just my public IP address, which I understand is the expected outcome.  I've double-checked that AdGuard is pointing to Unbound as an upstream server.  As a test, I've also shutdown the Unbound container and I lose DNS altogether as expected.  Is it normal for dnsleaktest.com to not show my public IP?

Thanks in advance!!

**Comment by whyscream** [comment]
https://github.com/MatthewVance/unbound-docker#override-default-forward By default, all queries are forwarded to Cloudflare, not to your ISP.

**Comment by MatthewVance** [comment]
@nuevilly, @whyscream is correct that the default behavior when using this container image is to forward all queries to Cloudflare. Specifically, it's this [line of code](https://github.com/MatthewVance/unbound-docker/blob/ba2d62b2f77aa2afb155b248cb71c7cc88ead01d/1.14.0/data/opt/unbound/etc/unbound/forward-records.conf#L11).

You're right that the udp connect failed is an ongoing issue. It doesn't affect anything and I keep hoping an upstream release will resolve it (I'm still seeing it in v1.14.0).

As for the other error suddenly appearing, that's odd. I'm not aware of any code changes around October 10. It's possible the container got rebuilt to pull OS updates, but that shouldn't cause that particular problem.

Are you still seeing this issue? Can you share what version of Unbound you're running and the command you use?

**Comment by nuevilly** [comment]
Thanks you, that all makes sense now!  The logfile error seems to have resolved itself for now..  Strange
