### ISSUE TITLE
timezone is wrong

### ISSUE THREAD

**Issue by Homer-Sim** [MatthewVance/unbound-docker#87]
Is there a chance to add correct timezone setting for unbound container?

**Comment by MatthewVance** [comment]
Personally, I much prefer the idea of staying with UTC. Can you elaborate on the issue or the particular setting you're after?

This article may be helpful: https://www.cloudsavvyit.com/12859/how-to-handle-timezones-in-docker-containers/

**Comment by MatthewVance** [comment]
Closing due to no feedback.
