### ISSUE TITLE
Disable forwarding mode

### ISSUE THREAD

**Issue by nuevilly** [MatthewVance/unbound-docker#96]
Hi,

The default config forwards DNS requests to Cloudflare.  What is the cleanest/simplest way of disabling forwarding mode so that Unbound queries the root servers directly?  

Should I just supply a forward-records.conf with the forward addresses commented out?  

Thanks!

**Comment by MatthewVance** [comment]
You’ll need to provide a full custom config as a volume mount.

**Comment by MatthewVance** [comment]
An alternative to providing a full config if you want to keep some of the defaults: https://github.com/MatthewVance/unbound-docker-rpi#append-customizations-to-the-provided-unbound-configuration. However, you'll need to uncomment this [line](https://github.com/MatthewVance/unbound-docker-rpi/blob/master/1.15.0/data/unbound.sh#L356) and re-build.

**Comment by nuevilly** [comment]
Thanks. Got it working.

To do this, I edited the default unbound.config file and commented out the line:
`include: /opt/unbound/etc/unbound/forward-records.conf`
