### ISSUE TITLE
unbound cannot open logfile /dev/null

### ISSUE THREAD

**Issue by yunxiangqin** [MatthewVance/unbound-docker#98]
**Describe the bug**
Unbound is working fine, but cannot open logfile /dev/null. This is the error message:
[1649626481] unbound[1:0] error: Could not open logfile /dev/null: Permission denied

Running the default configuration on docker on synology nas

**Comment by MatthewVance** [comment]
This is intended. The default config is set to not log for privacy reasons. /dev/null is a special Linux path.  

https://github.com/MatthewVance/unbound-docker/blob/95c2f71560714bc913eb6d056870efd0643285f4/1.15.0/data/unbound.sh#L86
